app/routes/auth_routes.py
from flask import Blueprint, render_template, redirect, url_for, request, flash, session
from flask_login import login_user, login_required, logout_user
from flask_wtf.csrf import generate_csrf
from werkzeug.security import check_password_hash
from models import User, Admin, Teacher, Student

auth_blueprint = Blueprint('auth', __name__)

@auth_blueprint.route('/login', methods=['GET'])
def login():
    """Route pour afficher le formulaire de connexion"""
    return render_template('login.html', csrf_token=generate_csrf())


@auth_blueprint.route('/login', methods=['POST'])
def login_form():
    """Route pour la connexion d'un utilisateur"""
    username = request.form['username']
    password = request.form['password']

    # Chercher l'utilisateur dans la base de données
    user = User.query.filter_by(username=username).first()
    pwhash = user.password if user else None
    if user and check_password_hash(pwhash, password):
        login_user(user)
        if user.role == 'student':
            session['student_id'] = Student.query.filter_by(user_id=user.id).first().id
            return redirect(url_for('dashboard.student_dashboard'))
        elif user.role == 'teacher':
            session['teacher_id'] = Teacher.query.filter_by(user_id=user.id).first().id
            return redirect(url_for('dashboard.teacher_dashboard'))
        elif user.role == 'admin':
            session['admin_id'] = Admin.query.filter_by(user_id=user.id).first().id
            return redirect(url_for('dashboard.admin_dashboard'))
        else:
            flash('Role inconnu', 'danger')
    else:
        flash(f'Username or password incorrect ', 'danger')
    return render_template('login.html', csrf_token=generate_csrf())

@auth_blueprint.route('/logout')
@login_required
def logout():
    """Route pour la déconnexion d'un utilisateur"""
    logout_user()
    return redirect(url_for('auth.login'))

app/routes/teacher_routes.py
from flask import Blueprint, render_template, redirect, url_for, request
from flask_login import login_required, current_user
from flask_wtf.csrf import generate_csrf

from models import Teacher, TeacherClass, Class, Student, Subject, Grade, Assignment, db

teacher_dashboard_blueprint = Blueprint('teacher_dashboard', __name__)


# ----- Routes pour l'espace enseignant ----- 

@teacher_dashboard_blueprint.route('/teacher_dashboard/grades', methods=['GET'])
@login_required
def grades():
    """Affiche les notes des élèves"""
    
    # Vérifier si l'utilisateur est connecté et est un enseignant
    if current_user.role != 'teacher':
        return redirect(url_for('home', csrf_token=generate_csrf()))
    
    teacher = Teacher.query.filter_by(user_id=current_user.id).first()
    teacherClasses = TeacherClass.query.filter_by(teacher_id=current_user.id).all()

    if not teacherClasses:
        # Put an error here
        return redirect(url_for('teacher_dashboard.'))
    
    # Classes
    classes_id: tuple[int] = tuple(set([tc.class_id for tc in teacherClasses]))
    classes_id = (1, 2, 3)
    classes = tuple(set([Class.query.filter_by(id=id).first() for id in classes_id]))
    classes_dict = sorted([{'id': class_.id, 'name': class_.class_name} for class_ in classes], key=lambda x: x['name'])

    # Matières
    subjects_id = tuple(set([tc.subject_id for tc in teacherClasses]))
    subjects = tuple(set([Subject.query.filter_by(id=id).first() for id in subjects_id]))
    subjects_dict = sorted([{'id': subject.id, 'name': subject.name} for subject in subjects], key=lambda x: x['name'])
    
    # Types de devoirs
    assignments = Assignment.query.all()
    assignments_dict = sorted([{'id': assignment.id, 'type': assignment.type} for assignment in assignments], key=lambda x: x['id'])
    
    # Initialiser les variables
    display_table = False
    students = []
    grades = []
    chosen_class = None
    chosen_subject = None
    chosen_assignment = None

    return render_template('teacher_templates/teacher_grades.html', teacher=teacher, display_table=display_table, subjects=subjects_dict, 
                           classes=classes_dict, assignments=assignments_dict, students=students, grades=grades, 
                           chosen_classe=chosen_class, chosen_subject=chosen_subject, chosen_assignment=chosen_assignment, 
                           grade_attributed=False, csrf_token=generate_csrf())
    
    
@teacher_dashboard_blueprint.route('/teacher_dashboard/grades', methods=['POST'])
@login_required
def grades_form():
    """Affiche les notes des élèves en fonction des filtres"""
    
    # Vérifier si l'utilisateur est connecté et est un enseignant
    if current_user.role != 'teacher':
        return redirect(url_for('home', csrf_token=generate_csrf()))
    
    
    # Récupérer la table de liaison entre les classes et les matières
    teacher = Teacher.query.filter_by(user_id=current_user.id).first()
    teacherClasses = TeacherClass.query.filter_by(teacher_id=current_user.id).all()

    if not teacherClasses:
        # Put an error here TODO
        return redirect(url_for('teacher_dashboard.'))
    
    # Récupérer les classes
    classes_id: tuple[int] = tuple(set([tc.class_id for tc in teacherClasses]))
    classes_id = (1, 2, 3)
    classes = tuple(set([Class.query.filter_by(id=id).first() for id in classes_id]))
    classes_dict = sorted([{'id': class_.id, 'name': class_.class_name} for class_ in classes], key=lambda x: x['name'])

    # Récupérer les matières
    subjects_id = tuple(set([tc.subject_id for tc in teacherClasses]))
    subjects = tuple(set([Subject.query.filter_by(id=id).first() for id in subjects_id]))
    subjects_dict = sorted([{'id': subject.id, 'name': subject.name} for subject in subjects], key=lambda x: x['name'])
    
    # Récupérer les types de devoirs
    assignments = Assignment.query.all()
    assignments_dict = sorted([{'id': assignment.id, 'type': assignment.type} for assignment in assignments], key=lambda x: x['id'])
    
    # Initialiser les variables
    display_table = False
    students = []
    grades = []
    chosen_class = None
    chosen_subject = None
    chosen_assignment = None
    
    action = request.form.get('action')
    if action == 'display':
        return display_grades(teacher, display_table, subjects_dict, classes_dict, assignments_dict, students, grades, chosen_class, chosen_subject, chosen_assignment)
    
    if action == 'update':
        return update_grades(teacher, display_table, subjects_dict, classes_dict, assignments_dict, students, grades, chosen_class, chosen_subject, chosen_assignment)


def display_grades(teacher, display_table, subjects_dict, classes_dict, assignments_dict, students, grades, chosen_class, chosen_subject, chosen_assignment):
    # Récupérer les valeurs du formulaire
    requested_class = request.form.get('class')
    requested_subject = request.form.get('subject')
    requested_assignment = request.form.get('assignment')
    
    # Si le formulaire "filtres" a été soumis
    if requested_class and requested_subject and requested_assignment:
        for class_dict in classes_dict:
            if class_dict['id'] == int(requested_class):
                chosen_class = class_dict
                break
    
        for subject_dict in subjects_dict:
            if subject_dict['id'] == int(requested_subject):
                chosen_subject = subject_dict
                break
            
        for assignment_dict in assignments_dict:
            if assignment_dict['id'] == int(requested_assignment):
                chosen_assignment = assignment_dict
                break
            
        display_table = True

        # Récupérer les étudiants
        students.extend(Student.query.filter_by(class_id=chosen_class['id']).all())

        # Récupérer les notes
        grades_list = []
        for student in students:
            grades_list.extend(Grade.query.filter_by(student_id=student.id).all())
        for grade in grades_list:
            grades.append({'grade': grade.grade, 
                            'student_id': grade.student_id, 
                            'subject_id': grade.subject_id,
                            'assignment_type_id': grade.assignment_type_id
                            })

        # Rajouter les notes manquantes
        for student in students:
            grade_found = False
            for grade in grades:
                if grade['student_id'] == student.id and grade['subject_id'] == chosen_subject['id'] and grade['assignment_type_id'] == chosen_assignment['id']:
                    grade_found = True
                    break
            if not grade_found:
                grades.append({'grade': '--', 'student_id': student.id, 'subject_id': chosen_subject['id'], 'assignment_type_id': chosen_assignment['id']})
                
        # Trier les notes selon les types de devoirs
        grades = [grade for grade in grades if grade['assignment_type_id'] == chosen_assignment['id']]
    
    return render_template('teacher_templates/teacher_grades.html', teacher=teacher, display_table=display_table, subjects=subjects_dict, 
                        classes=classes_dict, assignments=assignments_dict, students=students, grades=grades, 
                        chosen_classe=chosen_class, chosen_subject=chosen_subject, chosen_assignment=chosen_assignment, 
                        grade_attributed=False, csrf_token=generate_csrf())
    

def update_grades(teacher, display_table, subjects_dict, classes_dict, assignments_dict, students, grades, chosen_class, chosen_subject, chosen_assignment):
    """Mets à jour les notes des élèves"""
    
    # Vérifier si l'utilisateur est connecté et est un enseignant
    if current_user.role != 'teacher':
        return redirect(url_for('auth.login', csrf_token=generate_csrf()))
    
    # Récupérer les notes envoyés par le formulaire
    grades = request.form

    to_add = []  
    to_update = [] 

    # Parcourir tous les inputs dans grades
    for grade_key, grade_value in grades.items():
        if grade_value == '':
            continue
        if grade_key == 'csrf_token' or grade_key == 'action':
            continue
        
        # grade_key a la forme "student_id|subject_id"
        student_id, subject_id = map(int, grade_key.split('|'))  # Séparer et convertir en int
        
        # Vérifier si une note existe déjà pour cet étudiant et cette matière
        existing_grade = Grade.query.filter_by(student_id=student_id, subject_id=subject_id).first()

        if existing_grade:
            # Si la note existe, la mettre à jour
            existing_grade.grade = grade_value
            to_update.append(existing_grade)
        else:
            # Si la note n'existe pas, créer une nouvelle entrée
            new_grade = Grade(student_id=student_id, subject_id=subject_id, grade=grade_value, assignment_type_id=chosen_assignment['id'])
            to_add.append(new_grade)

    if to_add:
        db.session.bulk_save_objects(to_add)
    
    if to_update:
        db.session.bulk_update_mappings(Grade, [{'grade': grade.grade, 'student_id': grade.student_id, 'subject_id': grade.subject_id, 'assignment_type_id': grade.assignment_type_id} for grade in to_update])

    db.session.commit()
    
    return render_template('teacher_templates/teacher_grades.html', teacher=teacher, display_table=display_table, subjects=subjects_dict, 
                    classes=classes_dict, assignments=assignments_dict, students=students, grades=grades, 
                    chosen_classe=chosen_class, chosen_subject=chosen_subject, chosen_assignment=chosen_assignment, 
                    grade_attributed=False, csrf_token=generate_csrf())

@teacher_dashboard_blueprint.route('/teacher_dashboard/bulletins')
@login_required
def display_bulletins():
    """""" # TODO
    
    # Vérifier si l'utilisateur est connecté et est un enseignant

app/templates/teacher_templates/teacher_calendar.html
<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Agenda Hebdomadaire de {{ teacher.first_name }} {{ teacher.last_name }}</title>
        <link rel="stylesheet" href="{{ url_for('static', filename='style/style.css') }}">
    </head>

    <body>
        <a class="return-button" href="{{ url_for('dashboard.teacher_dashboard') }}">
            <img src="{{ url_for('static', filename='svg/arrow_back.svg') }}" alt="-> Dashboard">
        </a>

        <div class="dashboard">
            <div class="island">
                <h1>Agenda Hebdomadaire de {{ teacher.first_name }} {{ teacher.last_name }}</h1>
            </div>

            <div class="menu">
                <table class="calendar">
                    <thead>
                        <tr>
                            <th>Heure</th>
                            <th>Lundi</th>
                            <th>Mardi</th>
                            <th>Mercredi</th>
                            <th>Jeudi</th>
                            <th>Vendredi</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>08:00 - 09:00</td>
                            <td>Maths - 6ème</td>
                            <td>Physique - 3ème</td>
                            <td>Physique - 4ème </td>
                            <td></td>
                            <td>Physique - 5ème</td>
                        </tr>
                        <tr>
                            <td>09:00 - 10:00</td>
                            <td>Physique - 3ème</td>
                            <td>Maths - 6ème</td>
                            <td></td>
                            <td>Maths - 5ème</td>
                            <td>Physique - 6ème</td>
                        </tr>
                        <tr>
                            <td>10:00 - 11:00</td>
                            <td></td>
                            <td></td>
                            <td>Maths - 4ème</td>
                            <td>Chimie - 6ème</td>
                            <td></td>
                        </tr>
                        <tr>
                            <td>11:00 - 12:00</td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>
                        <tr>
                            <td>14:00 - 15:00</td>
                            <td>Physique - 5ème</td>
                            <td></td>
                            <td>Maths - 5ème</td>
                            <td></td>
                            <td>Chimie - 6ème</td>
                        </tr>
                        <tr>
                            <td>15:00 - 16:00</td>
                            <td>Physique - 5ème</td>
                            <td></td>
                            <td>Chimie - 6ème</td>
                            <td></td>
                            <td></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </body>
</html>

app/templates/teacher_templates/teacher_dashboard.html
<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Dashboard</title>
        <link rel="stylesheet" href="{{ url_for('static', filename='style/style.css') }}">
    </head>
    <body>
        <div class="dashboard">
            <div class="island">
                <h1>Bienvenue</h1>
                <h2>Sélectionnez une option dans le menu</h2>
            </div>

            <div class="menu">
                <div class="menu-part">
                    <a href="{{ url_for('teacher_dashboard.grades') }}">
                        <button>
                            <img src="{{ url_for('static', filename='svg/notes.svg') }}" alt="Notes">
                            <h3>Notes</h3>
                        </button>
                    </a>
                    <a>
                        <button>
                            <img src="{{ url_for('static', filename='svg/bulletin.svg') }}" alt="Bulletins">
                            <h3>Bulletins</h3>
                        </button>
                    </a>
                    <a href="{{ url_for('teacher_dashboard.display_calendar') }}">
                        <button>
                            <img src="{{ url_for('static', filename='svg/agenda.svg') }}" alt="Messagerie">
                            <h3>Agenda</h3>
                        </button>
                    </a>
                </div>
                <div class="menu-part">
                    <a href="{{ url_for('teacher_dashboard.display_students') }}">
                        <button>
                            <img src="{{ url_for('static', filename='svg/students.svg') }}" alt="Élèves">
                            <h3>Élèves</h3>
                        </button>
                    </a>
                    <a href="{{ url_for('teacher_dashboard.display_settings') }}">
                        <button>
                            <img src="{{ url_for('static', filename='svg/settings.svg') }}" alt="Paramètres">
                            <h3>Paramètres</h3>
                        </button>
                    </a>
                    <a href="{{ url_for('auth.logout') }}">
                        <button>
                            <img src="{{ url_for('static', filename='svg/logout.svg') }}" alt="Déconnexion">
                            <h3>Déconnexion</h3>
                        </button>
                    </a>
                </div>
            </div>
        </div>
    </body>
</html>

app/templates/teacher_templates/teacher_grades.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Modifier des notes {{ teacher.first_name }} {{ teacher.last_name }}</title>
        <link rel="stylesheet" href="{{ url_for('static', filename='style/style.css') }}">
    </head>
    <body>
        <a class="return-button" href="{{ url_for('dashboard.teacher_dashboard') }}">
            <img src="{{ url_for('static', filename='svg/arrow_back.svg') }}" alt="-> Dashboard">
        </a>

        <!-- Grade filter section-->
        <div class="dashboard">
            <div class="island">
                <h1>Voici les notes, {{ teacher.first_name }} {{ teacher.last_name }}</h1>
            </div>

            <div class="menu">
                <h2>Modifiez des notes</h2>

                <form class="prof-notes-table" action="{{ url_for('.grades') }}" method="POST">
                    <input type="hidden" name="csrf_token" value="{{ csrf_token }}">
                    <div class="">
                        <div>
                            <label for="subject">Subject</label>
                            <select name="subject" id="subject">
                                <option value="">-- Select Subject --</option>
                                {% for subject in subjects %}
                                    <option value="{{ subject.id }}">{{ subject['name'] }}</option>
                                {% endfor %}
                            </select>
                        </div>

                        <div>
                            <label for="class">Class</label>
                            <select name="class" id="class">
                                <option value="">-- Select Class --</option>
                                {% for class in classes %}
                                    <option value="{{ class.id }}">{{ class['name'] }}</option>
                                {% endfor %}
                            </select>
                        </div>

                        <div>
                            <label for="subject">Subject</label>
                            <select name="assignment" id="assignment">
                                <option value="">-- Select Assignment --</option>
                                {% for assignment in assignments %}
                                    <option value="{{ assignment.id }}">{{ assignment['type'] }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>

                    <button type="submit" name="action" value="display">Display</button>
                </form>

                <!-- Grade display section-->
                <form class="prof-notes-table" action="{{ url_for('.grades') }}" method="POST">
                    <input type="hidden" name="csrf_token" value="{{ csrf_token }}">
                    {% if display_table %}
                    <table>
                        <thead>
                            <th>Last name</th>
                            <th>First name</th>
                            <th>{{ chosen_subject['name'] }} - {{ chosen_assignment['type'] }}</th>
                        </thead>
                
                        <tbody>
                            {% for student in students %}
                                {% set grade_attributed = False %}
                                <tr>
                                    <th>{{ student.last_name }}</th>
                                    <th>{{ student.first_name }}</th>
                                    <th>
                                        {% for grade in grades %}
                                            {% if grade.student_id == student.id and grade.subject_id == chosen_subject['id'] %}
                                                <input type="text" placeholder="{{ grade.grade }}" maxlength="2" name="{{ student.id }}|{{ chosen_subject.id }}">
                                                {% set grade_attributed = True %}
                                            {% endif %}
                                        {% endfor %}
                                    </th>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                    <button type="submit" name="action" value="update" id="save-button">Save</button>
                </form>
                {% endif %}
            </div>
        </div>
    </body>
</html>

app/templates/teacher_templates/teacher_settings.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Modifier les paramètres {{ teacher.first_name }} {{ teacher.last_name }}</title>
        <link rel="stylesheet" href="{{ url_for('static', filename='style/style.css') }}">
    </head>
    <body>
        <a class="return-button" href="{{ url_for('dashboard.teacher_dashboard') }}">
            <img src="{{ url_for('static', filename='svg/arrow_back.svg') }}" alt="-> Dashboard">
        </a>

        <div class="dashboard">
            <div class="island">
                <h1>Paramètres de {{ teacher.first_name }} {{ teacher.last_name }}</h1>
            </div>

            <div class="menu">
                <h2>Modifiez des paramètres</h2>

                <div class="settings">
                    <div class="disabled-message">Ces paramètres sont bloqués par l'administrateur.</div>
                    
                    <div class="setting-list">
                        <div>
                            <span>Mode sombre</span>
                            <input type="checkbox" disabled>
                        </div>
                        <div>
                            <span>Notifications</span>
                            <input type="checkbox" disabled>
                        </div>
                        <div>
                            <span>Langue</span>
                            <select disabled>
                                <option>Français</option>
                                <option>Anglais</option>
                            </select>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>

app/templates/teacher_templates/teacher_students.html
<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Vos Élèves</title>
        <link rel="stylesheet" href="{{ url_for('static', filename='style/style.css') }}">
    </head>

    <body>
        <a class="return-button" href="{{ url_for('dashboard.teacher_dashboard') }}">
            <img src="{{ url_for('static', filename='svg/arrow_back.svg') }}" alt="-> Dashboard">
        </a>

        <div class="dashboard">
            <div class="island">
                <h1>Voici vos élèves</h1>
            </div>

            <div class="menu">
                <table>
                    <thead>
                        <tr>
                            <th>Élève</th>
                            <th>Classe</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for student in students %}
                            <tr>
                                <td>{{ student.name }}</td>
                                <td>{{ student.class_name }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </body>
</html>