app/routes/admin_routes.py
from flask import Blueprint, render_template, redirect, url_for, request
from flask_login import login_required, current_user
from werkzeug.security import generate_password_hash
from flask_wtf.csrf import generate_csrf

from models import User, Admin, Student, Teacher, Class, TeacherClass, TeacherSubject, Grade, Subject, db

admin_dashboard_blueprint = Blueprint('admin_dashboard', __name__)


# ----- Routes pour l'espace administrateur -----

# --- Gestion des Étudiants ---
@admin_dashboard_blueprint.route('/admin_dashboard/student_modification', methods=['GET'])
@login_required
def student_modification():
    """Affiche la page de gestion des étudiants."""
    
    # Vérifier si l'utilisateur est connecté et est un administrateur
    if current_user.role != 'admin':
        return redirect(url_for('auth.login', csrf_token=generate_csrf()))

    context = get_common_context(Student, 'admin_templates/student_modification.html')
    return render_page(context)


@admin_dashboard_blueprint.route('/admin_dashboard/student_modification', methods=['POST'])
@login_required
def student_modification_form():
    """Gère les actions POST pour la gestion des étudiants."""
    
    # Vérifier si l'utilisateur est connecté et est un administrateur
    if current_user.role != 'admin':
        return redirect(url_for('auth.login', csrf_token=generate_csrf()))

    context = get_common_context(Student, 'admin_templates/student_modification.html')
    return handle_post_request(request, context, create_student, modify_student, delete_student)

def create_student(request, context):
    """Crée un étudiant."""
    first_name, last_name, class_id = request.form.get('first_name'), request.form.get('last_name'), request.form.get('selected_class')
    username, password, confirmed_password = request.form.get('username'), request.form.get('password'), request.form.get('confirmed_password')

    # Vérifier si tous les champs sont remplis
    if not all([first_name, last_name, class_id]):
        context['error_message'] = "Tous les champs doivent être remplis."
        return render_page(context)

    # Créer un utilisateur
    user, msg = create_user(username, password, confirmed_password, 'student')
    if not user:
        context['error_message'] = msg
        return render_page(context)

    # Créer un étudiant
    student = Student(first_name=first_name, last_name=last_name, class_id=int(class_id), user_id=user.id)
    db.session.add(student)
    db.session.commit()
    
    return redirect(url_for('admin_dashboard.student_modification', csrf_token=generate_csrf()))

def modify_student(request, context):
    """Modifie un étudiant."""
    student_id = request.form.get('new_chosen_student_id')
    
    # Vérifier si l'étudiant existe
    student = Student.query.get(student_id)
    if not student:
        context['error_message'] = "Étudiant introuvable."
        return render_page(context)

    # Mettre à jour les informations de l'étudiant
    student.first_name = request.form.get('first_name')
    student.last_name = request.form.get('last_name')
    student.class_id = int(request.form.get('selected_class'))

    # Mettre à jour l'utilisateur associé
    user = User.query.get(student.user_id)
    user.username = request.form.get('username')
    user.password = generate_password_hash(request.form.get('password')) if request.form.get('password') else user.password

    db.session.commit()
    return redirect(url_for('admin_dashboard.student_modification', csrf_token=generate_csrf()))

# --- Gestion des Enseignants ---
@admin_dashboard_blueprint.route('/admin_dashboard/teacher_modification', methods=['GET'])
@login_required
def teacher_modification():
    """Affiche la page de gestion des enseignants."""
    
    # Vérifier si l'utilisateur est connecté et est un administrateur
    if current_user.role != 'admin':
        return redirect(url_for('auth.login', csrf_token=generate_csrf()))

    context = get_common_context(Teacher, 'admin_templates/teacher_modification.html')
    return render_page(context)

    
@admin_dashboard_blueprint.route('/admin_dashboard/teacher_modification', methods=['POST'])
@login_required
def teacher_modification_form():
    """Gère les actions POST pour la gestion des enseignants."""
    
    # Vérifier si l'utilisateur est connecté et est un administrateur
    if current_user.role != 'admin':
        return redirect(url_for('auth.login', csrf_token=generate_csrf()))

    context = get_common_context(Teacher, 'admin_templates/teacher_modification.html')
    return handle_post_request(request, context, create_teacher, modify_teacher, delete_teacher)

def create_teacher(request, context):
    """Crée un enseignant."""
    first_name, last_name = request.form.get('first_name'), request.form.get('last_name')
    username, password, confirmed_password = request.form.get('username'), request.form.get('password'), request.form.get('confirmed_password')

    # Vérifier si tous les champs sont remplis
    if not all([first_name, last_name]):
        context['error_message'] = "Tous les champs doivent être remplis."
        return render_page(context)

    # Créer un utilisateur
    user, msg = create_user(username, password, confirmed_password, 'teacher')
    if not user:
        context['error_message'] = msg
        return render_page(context)

    # Créer un enseignant
    teacher = Teacher(first_name=first_name, last_name=last_name, user_id=user.id)
    db.session.add(teacher)
    db.session.commit()
    
    
    # Mettre à jour les classes dont il est professeur principal
    head_teacher_classes = request.form.getlist('head_teacher_classes')
    for class_ in Class.query.all():
        class_.head_teacher_id = teacher.id if str(class_.id) in head_teacher_classes else None

    # Mettre à jour les matières enseignées
    selected_subjects = request.form.getlist('teacher_subjects')
    TeacherSubject.query.filter_by(teacher_id=teacher.id).delete()
    db.session.add_all([TeacherSubject(teacher_id=teacher.id, subject_id=int(subj_id)) for subj_id in selected_subjects])

    # Mettre à jour les matières enseignées par classe
    TeacherClass.query.filter_by(teacher_id=teacher.id).delete()
    for key in request.form:
        if "|" in key:  # Exemple : "class_id|subject_id"
            class_id, subject_id = key.split("|")
            db.session.add(TeacherClass(teacher_id=teacher.id, class_id=int(class_id), subject_id=int(subject_id)))
    
    db.session.commit()
    return redirect(url_for('admin_dashboard.teacher_modification', csrf_token=generate_csrf()))

def modify_teacher(request, context):
    """Modifie un enseignant et met à jour ses matières et classes."""
    teacher_id = request.form.get('new_chosen_teacher_id')
    
    # Vérifier si l'enseignant existe
    teacher = Teacher.query.get(teacher_id)
    if not teacher:
        context['error_message'] = "Enseignant introuvable."
        return render_page(context)

    teacher.first_name = request.form.get('first_name')
    teacher.last_name = request.form.get('last_name')

    # Mettre à jour les classes dont il est professeur principal
    head_teacher_classes = request.form.getlist('head_teacher_classes')
    for class_ in Class.query.all():
        class_.head_teacher_id = teacher.id if str(class_.id) in head_teacher_classes else None

    # Mettre à jour les matières enseignées
    selected_subjects = request.form.getlist('teacher_subjects')
    TeacherSubject.query.filter_by(teacher_id=teacher.id).delete()
    db.session.add_all([TeacherSubject(teacher_id=teacher.id, subject_id=int(subj_id)) for subj_id in selected_subjects])

    # Mettre à jour les matières enseignées par classe
    TeacherClass.query.filter_by(teacher_id=teacher.id).delete()
    for key in request.form:
        if "|" in key:  # Exemple : "class_id|subject_id"
            class_id, subject_id = key.split("|")
            db.session.add(TeacherClass(teacher_id=teacher.id, class_id=int(class_id), subject_id=int(subject_id)))

    # Mettre à jour l'utilisateur associé
    user = User.query.get(teacher.user_id)
    user.username = request.form.get('username')
    user.password = generate_password_hash(request.form.get('password')) if request.form.get('password') else user.password


    db.session.commit()
    return redirect(url_for('admin_dashboard.teacher_modification', csrf_token=generate_csrf()))

# --- Gestion des Administrateurs ---
@admin_dashboard_blueprint.route('/admin_dashboard/admin_modification', methods=['GET'])
@login_required
def admin_modification():
    """Affiche la page de gestion des administrateurs."""
    
    # Vérifier si l'utilisateur est connecté et est un administrateur
    if current_user.role != 'admin':
        return redirect(url_for('auth.login', csrf_token=generate_csrf()))

    context = get_common_context(Admin, 'admin_templates/admin_modification.html')
    return render_page(context)


@admin_dashboard_blueprint.route('/admin_dashboard/admin_modification', methods=['POST'])
@login_required
def admin_modification_form():
    """Gère les actions POST pour la gestion des administrateurs."""
    
    # Vérifier si l'utilisateur est connecté et est un administrateur
    if current_user.role != 'admin':
        return redirect(url_for('auth.login', csrf_token=generate_csrf()))

    context = get_common_context(Admin, 'admin_templates/admin_modification.html')
    return handle_post_request(request, context, create_admin, modify_admin, delete_admin)

def create_admin(request, context):
    """Crée un administrateur."""
    first_name, last_name = request.form.get('first_name'), request.form.get('last_name')
    username, password, confirmed_password = request.form.get('username'), request.form.get('password'), request.form.get('confirmed_password')

    # Vérifier si tous les champs sont remplis
    if not all([first_name, last_name]):
        context['error_message'] = "Tous les champs doivent être remplis."

app/routes/auth_routes.py
from flask import Blueprint, render_template, redirect, url_for, request, flash, session
from flask_login import login_user, login_required, logout_user
from flask_wtf.csrf import generate_csrf
from werkzeug.security import check_password_hash
from models import User, Admin, Teacher, Student

auth_blueprint = Blueprint('auth', __name__)

@auth_blueprint.route('/login', methods=['GET'])
def login():
    """Route pour afficher le formulaire de connexion"""
    return render_template('login.html', csrf_token=generate_csrf())


@auth_blueprint.route('/login', methods=['POST'])
def login_form():
    """Route pour la connexion d'un utilisateur"""
    username = request.form['username']
    password = request.form['password']

    # Chercher l'utilisateur dans la base de données
    user = User.query.filter_by(username=username).first()
    pwhash = user.password if user else None
    if user and check_password_hash(pwhash, password):
        login_user(user)
        if user.role == 'student':
            session['student_id'] = Student.query.filter_by(user_id=user.id).first().id
            return redirect(url_for('dashboard.student_dashboard'))
        elif user.role == 'teacher':
            session['teacher_id'] = Teacher.query.filter_by(user_id=user.id).first().id
            return redirect(url_for('dashboard.teacher_dashboard'))
        elif user.role == 'admin':
            session['admin_id'] = Admin.query.filter_by(user_id=user.id).first().id
            return redirect(url_for('dashboard.admin_dashboard'))
        else:
            flash('Role inconnu', 'danger')
    else:
        flash(f'Username or password incorrect ', 'danger')
    return render_template('login.html', csrf_token=generate_csrf())

@auth_blueprint.route('/logout')
@login_required
def logout():
    """Route pour la déconnexion d'un utilisateur"""
    logout_user()
    return redirect(url_for('auth.login'))

app/templates/admin_templates/admin_dashboard.html
<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="UTF-8">
        <title>Admin Dashboard</title>
        <link rel="stylesheet" href="{{ url_for('static', filename='style/style.css') }}">
    </head>
    <body>
        <div class="dashboard">
            <div class="island">
                <h1>Bienvenue</h1>
                <h2>Sélectionnez une option dans le menu</h2>
            </div>

            <div class="menu menu-admin">
                <div class="menu-part">
                    <a href="{{ url_for('admin_dashboard.student_modification') }}">
                        <button>
                            <img src="{{ url_for('static', filename='svg/students.svg') }}" alt="Notes">
                            <h3>Elèves</h3>
                        </button>
                    </a>
                    <a href="{{ url_for('admin_dashboard.teacher_modification') }}">
                        <button>
                            <img src="{{ url_for('static', filename='svg/teachers.svg') }}" alt="Bulletins">
                            <h3>Professeurs</h3>
                        </button>
                    </a>
                </div>
                <div class="menu-part">
                    <a href="{{ url_for('admin_dashboard.admin_modification') }}">
                        <button>
                            <img src="{{ url_for('static', filename='svg/admin.svg') }}" alt="Messagerie">
                            <h3>Administrateurs</h3>
                        </button>
                    </a>
                    <a href="{{ url_for('auth.logout') }}">
                        <button>
                            <img src="{{ url_for('static', filename='svg/logout.svg') }}" alt="Déconnexion">
                            <h3>Déconnexion</h3>
                        </button>
                    </a>
                </div>
            </div>
        </div>
    </body>
</html>

app/templates/admin_templates/admin_modification.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Gestion des Administrateurs</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='style/style.css') }}">
</head>

<body>
    <a class="return-button" href="{{ url_for('dashboard.admin_dashboard') }}">
        <img src="{{ url_for('static', filename='svg/arrow_back.svg') }}" alt="-> Dashboard">
    </a>

    {% if error_message %}
        <div class="error-message">{{ error_message }}</div>
    {% endif %}

    {% if success_message %}
        <div class="success-message">{{ success_message }}</div>
    {% endif %}

    <!-- Sélection d'un administrateur -->
    <div class="dashboard">
        <div class="island">
            <h1>Vous pouvez modifier la liste des admins</h1>
        </div>

        <div class="menu editer-admin">
            <div class="top-div-modifyer">
                <form class="display-people" action="{{ url_for('.admin_modification') }}" method="POST">
                    <input type="hidden" name="csrf_token" value="{{ csrf_token }}">
                    <select name="chosen_entity_id" size="10">
                        {% for admin in entities_dict %}
                            <option value="{{ admin['id'] }}">{{ admin['first_name'] }} {{ admin['last_name'] }}</option>
                        {% endfor %}
                    </select>
                    <div>
                        <button name="action" value="display" type="submit">Afficher</button>
                        <button name="action" value="create" type="submit">Créer un nouvel administrateur</button>
                    </div>
                </form>

                {% if chosen_entity or new_entity %}
                    <!-- Formulaire de modification / création -->
                    <form class="modify-people" action="{{ url_for('.admin_modification') }}" method="POST">
                        <input type="hidden" name="csrf_token" value="{{ csrf_token }}">
                        <input type="hidden" name="new_chosen_admin_id" value="{{ chosen_entity.id if chosen_entity else '' }}">

                        <div>
                            <label>Prénom</label>
                            <input type="text" name="first_name" value="{{ chosen_entity.first_name if chosen_entity else '' }}">
                        </div>

                        <div>
                            <label>Nom</label>
                            <input type="text" name="last_name" value="{{ chosen_entity.last_name if chosen_entity else '' }}">
                        </div>

                        <div>
                            <label>Nom d'utilisateur</label>
                            <input type="text" name="username" value="{{ chosen_entity.username if chosen_entity else '' }}">
                        </div>

                        <div>
                            <label>Mot de passe</label>
                            <input type="password" name="password">
                        </div>

                        <div>
                            <label>Confirmer Mot de passe</label>
                            <input type="password" name="confirmed_password">
                        </div>

                        <div class="buttons-validate">
                            <button type="submit" name="action" value="{% if new_entity %}create_save{% else %}modify{% endif %}">Sauvegarder</button>
                            <button type="submit" name="action" value="delete" onclick="return confirmDelete()">Supprimer</button>
                        </div>
                    </form>
                {% endif %}
            </div>
        </div>
    </div>

    <script>
        function confirmDelete() {
            return confirm("Êtes-vous sûr de vouloir supprimer cet administrateur définitivement ?");
        }
    </script>
</body>
</html>

app/templates/admin_templates/student_modification.html
<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Gestion des Élèves</title>
        <link rel="stylesheet" href="{{ url_for('static', filename='style/style.css') }}">
    </head>

    <body>
        <a class="return-button" href="{{ url_for('dashboard.admin_dashboard') }}">
            <img src="{{ url_for('static', filename='svg/arrow_back.svg') }}" alt="-> Dashboard">
        </a>

        {% if error_message %}
            <div style="color: red;">{{ error_message }}</div>
        {% endif %}

        {% if success_message %}
            <div style="color: green;">{{ success_message }}</div>
        {% endif %}

        <!-- Sélection d'un élève -->
        <div class="dashboard">
            <div class="island">
                <h1>Vous pouvez modifier la liste d'élèves</h1>
            </div>

            <div class="menu editer-admin">
                <div class="top-div-modifyer">
                    <form class="display-people" action="{{ url_for('.student_modification') }}" method="POST">
                        <input type="hidden" name="csrf_token" value="{{ csrf_token }}">
                        <select name="chosen_entity_id" size="10">
                            {% for student in entities_dict %}
                                <option value="{{ student['id'] }}">
                                    [{{ classes_dict[student['class_id']] }}] {{ student['first_name'] }} {{ student['last_name'] }}
                                </option>
                            {% endfor %}
                        </select>
                        <div>
                            <button name="action" value="display" type="submit">Afficher</button>
                            <button name="action" value="create" type="submit">Créer un nouvel élève</button>
                        </div>
                    </form>

                    {% if chosen_entity or new_entity %}
                        <!-- Formulaire de modification / création -->
                        <form class="modify-people" action="{{ url_for('.student_modification') }}" method="POST">
                            <input type="hidden" name="csrf_token" value="{{ csrf_token }}">
                            <input type="hidden" name="new_chosen_student_id" value="{{ chosen_entity.id if chosen_entity else '' }}">

                            <div>
                                <label>Prénom</label>
                                <input type="text" name="first_name" value="{{ chosen_entity.first_name if chosen_entity else '' }}">
                            </div>

                            <div>
                                <label>Nom</label>
                                <input type="text" name="last_name" value="{{ chosen_entity.last_name if chosen_entity else '' }}">
                            </div>

                            <div>
                                <label>Nom d'utilisateur</label>
                                <input type="text" name="username" value="{{ chosen_entity.username if chosen_entity else '' }}">
                            </div>

                            <div>
                                <label>Mot de passe</label>
                                <input type="password" name="password">
                            </div>

                            <div>
                                <label>Confirmer Mot de passe</label>
                                <input type="password" name="confirmed_password">
                            </div>

                            <div>
                                <label>Classe</label>
                                <select name="selected_class">
                                    {% for class_id, class_name in classes_dict.items() %}
                                        <option value="{{ class_id }}" {% if chosen_entity and class_id == chosen_entity.class_id %}selected{% endif %}>
                                            {{ class_name }}
                                        </option>
                                    {% endfor %}
                                </select>
                            </div>

                            <div class="buttons-validate">
                                <button type="submit" name="action" value="{% if new_entity %}create_save{% else %}modify{% endif %}">Sauvegarder</button>
                                <button type="submit" name="action" value="delete" onclick="return confirmDelete()">Supprimer</button>
                            </div>
                        </form>
                    {% endif %}
                </div>
            </div>
        </div>

        <script>
            function confirmDelete() {
                return confirm("Êtes-vous sûr de vouloir supprimer cet élève définitivement ?");
            }
        </script>
    </body>
</html>

app/templates/admin_templates/teacher_modification.html
<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Gestion des Professeurs</title>
        <link rel="stylesheet" href="{{ url_for('static', filename='style/style.css') }}">
    </head>

    <body>
        <a class="return-button" href="{{ url_for('dashboard.admin_dashboard') }}">
            <img src="{{ url_for('static', filename='svg/arrow_back.svg') }}" alt="-> Dashboard">
        </a>

        {% if error_message %}
            <div style="color: red;">{{ error_message }}</div>
        {% endif %}

        {% if success_message %}
            <div style="color: green;">{{ success_message }}</div>
        {% endif %}

        <!-- Sélection d'un professeur -->
        <div class="dashboard">
            <div class="island">
                <h1>Vous pouvez modifier la liste des professeurs</h1>
            </div>

            <div class="menu editer-admin">
                <div class="top-div-modifyer">
                    <form class="display-people" action="{{ url_for('.teacher_modification') }}" method="POST">
                        <input type="hidden" name="csrf_token" value="{{ csrf_token }}">
                        <select name="chosen_entity_id" size="10">
                            {% for teacher in entities_dict %}
                                <option value="{{ teacher['id'] }}">{{ teacher['first_name'] }} {{ teacher['last_name'] }}</option>
                            {% endfor %}
                        </select>
                        <div>
                            <button name="action" value="display" type="submit">Afficher</button>
                            <button name="action" value="create" type="submit">Créer un nouveau professeur</button>
                        </div>
                    </form>

                    {% if chosen_entity or new_entity %}
                        <!-- Formulaire de modification / création -->
                        <form class="modify-people" action="{{ url_for('.teacher_modification') }}" method="POST">
                            <input type="hidden" name="csrf_token" value="{{ csrf_token }}">
                            <input type="hidden" name="new_chosen_teacher_id" value="{{ chosen_entity.id if chosen_entity else '' }}">

                            <div>
                                <label>Prénom</label>
                                <input type="text" name="first_name" value="{{ chosen_entity.first_name if chosen_entity else '' }}">
                            </div>

                            <div>
                                <label>Nom</label>
                                <input type="text" name="last_name" value="{{ chosen_entity.last_name if chosen_entity else '' }}">
                            </div>

                            <div>
                                <label>Nom d'utilisateur</label>
                                <input type="text" name="username" value="{{ chosen_entity.username if chosen_entity else '' }}">
                            </div>

                            <div>
                                <label>Mot de passe</label>
                                <input type="password" name="password">
                            </div>

                            <div>
                                <label>Confirmer Mot de passe</label>
                                <input type="password" name="confirmed_password">
                            </div>

                            <table>
                                <thead>
                                    <tr>
                                        <th>Professeur principal de :</th>
                                        <th>Attribuer</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for class_id, class_name in classes_dict.items() %}
                                    <tr>
                                        <td>{{ class_name }}</td>
                                        <td>
                                            <input type="checkbox" name="head_teacher_classes" value="{{ class_id }}"
                                                {% if chosen_entity and class_id in chosen_entity.head_teacher_classes %}checked{% endif %}>
                                        </td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </form>
                    {% endif %}
                </div>       
                    
                <div class="bottom-div-modifyer">
                    {% if chosen_entity or new_entity %}
                        <form class="modify-people" action="{{ url_for('.teacher_modification') }}" method="POST">
                            <table>
                                <thead>
                                    <tr>
                                        <th>Compétences (Matières enseignées)</th>
                                        {% for subject_id, subject_name in subjects_dict.items() %}
                                            <th>{{ subject_name }}</th>
                                        {% endfor %}
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td>Enseigne</td>
                                        {% for subject_id, subject_name in subjects_dict.items() %}
                                            <td>
                                                <input type="checkbox" name="teacher_subjects" value="{{ subject_id }}"
                                                    {% if chosen_entity and subject_id in chosen_entity.subjects %}checked{% endif %}>
                                            </td>
                                        {% endfor %}
                                    </tr>
                                </tbody>
                            </table>
                            

                            <table>
                                <thead>
                                    <tr>
                                        <th>Enseignement par classe</th>
                                        {% for subject_id, subject_name in subjects_dict.items() %}
                                            <th>{{ subject_name }}</th>
                                        {% endfor %}
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for class_id, class_name in classes_dict.items() %}
                                        <tr>
                                            <td><strong>{{ class_name }}</strong></td>
                                            {% for subject_id, subject_name in subjects_dict.items() %}
                                                <td>
                                                    <input type="checkbox" name="{{ class_id }}|{{ subject_id }}"
                                                        {% if chosen_entity.id and (chosen_entity.id, class_id) in teacher_classes_dict and 
                                                            subject_id in teacher_classes_dict[(chosen_entity.id, class_id)] %}checked{% endif %}>
                                                </td>
                                            {% endfor %}
                                        </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                            

                            <div class="buttons-validate">
                                <button type="submit" name="action" value="{% if new_entity %}create_save{% else %}modify{% endif %}">Sauvegarder</button>
                                <button type="submit" name="action" value="delete" onclick="return confirmDelete()">Supprimer</button>
                            </div>
                        </form>
                    {% endif %}
                </div>
            </div>
        </div>

        <script>
            function confirmDelete() {
                return confirm("Êtes-vous sûr de vouloir supprimer ce professeur définitivement ?");
            }
        </script>
    </body>
</html>